changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🛠 Breaking Changes"
      labels: [breaking-change]
    - title: "✨ Features"
      labels: [feat]
    - title: "🐛 Bug Fixes"
      labels: [fix]
    - title: "🔒 Security"
      labels: [security]
    - title: "♻️ Refactors"
      labels: [refactor]
    - title: "🧹 Maintenance"
      labels: [chore, dependencies]
    - title: "📝 Documentation"
      labels: [docs]
    - title: "Other Changes"
      labels: ["*"]
